# minecraft defines the minecraft agent connections and behavior
minecraft:
  # optional timeout time in ms
  connectTimeout: 10000
  # optional profile directory (see bedrock-protocol docs)
  profilesFolder: "C:\\projects\\pocket_prattle\\profiles"
  servers:
    # under minecraft.servers, define servers using short names
    survival:
      # connection details, required
      host: my-server.com
      port: 19132
      # relay defines minecraft <-> discord chat routing (optional)
      routing:
        # default settings are designated with {}
        my_discord_channel: {}
        my_logging_discord:
          # only send messages to discord, never receive
          type: log
    creative:
      host: my-server.com
      port: 19134
      routing:
        my_other_discord_channel: {}
        # multiple minecraft servers can point to the same channel
        my_logging_discord:
          type: log
web:
  # prometheus client web server details - an http endpoint for server stats
  host: localhost
  port: 3333
discord:
  # discord app details.
  # https://discordpy.readthedocs.io/en/stable/discord.html
  # Only "create hooks" permission is recommended at this time (but unused).
  token: 'discord.bot.token.12345'
  app_id: 'discord.bot.app.id'
  # a bots nickname can be set globally ...
  nick: 'General Discord Nickname'
  channels:
    my_discord_channel:
      guild: '12345'
      channel: '67890'
      # ... or in the channel config (set at the guild/server level though)
      nick: 'Specific Discord Name'
    my_other_discord_channel:
      # NOTE: guild and channel must be strings (blame ieee 754)
      guild: '12345'
      channel: '67891'
    my_logging_discord:
      guild: '54321'
      channel: '09876'